### ISSUE TITLE
I have a few questions, sorry for the issue. [ QUESTION ]

### ISSUE THREAD

**Issue by zekageri** [jeremypoulter/ArduinoMongoose#15]
What is the license of this lib?

Does it work with LITTLEFS?
Can i serve pages from the file system?

Does http post and get working?
Is websocket working and stabil?

Sorry for the questions.

**Comment by jeremypoulter** [comment]
Ah sorry yes, no licence, I think it has to be GPL due to the parasitic nature of that I will look into it. I have not added any support for serving from a file system in this library but is supported by Mongoose, not sure about LittleFS however. 

WebSockets work well in my main usecase and they are used quite heavily.

**Comment by zekageri** [comment]
Oh nice. GPL or LGPL would be really good. Do you plan to support file systems? I want to port my code from Me_no_Dev's async lib to this, because this is really promising, but i'm using LITTLE FS on esp32 and i really want to keep that to serve pages from the file system. Also heavily using POST and GET requests too but the websocket on that lib is running me craazyy

**Comment by jeremypoulter** [comment]
On the licensing, Mongoose can be used under GPLv2 according to https://cesanta.com/licensing.html so you should be good there. I will officially post a Licence agreement once I confirm how to interact with Cesanta's commercial licence.

On Little FS I did do some initial investigation into filesystem support but it is a little tricky with Mongoose v6. From what I have been reading v7 should make this a little easier so that may be a pre-requisite. Unfortunately I don't have the bandwidth to do either of those tasks right now :( However if you are just serving static content maybe consider embedding the content into the firmware (see https://github.com/OpenEVSE/ESP32_WiFi_V3.x/ for an example) this makes OTA upgrades much simpler.

**Comment by zekageri** [comment]
Unfortunatelly i can't embed the files because i have to do upgrades to the webpages separatelly. 

My current setup is that i can replace files one by one from web if i want to and i can upgrade the firmware separate from the web. I have built a file system interaction ui thingy where i can manipulate the files in the file system as much as i want. i can download, upload, delete, replace these files and i want it to stay that way. If i embed these files into the firmware, like a webpage html to PROGMEM i would have to write these again. This is super easy for me that way, and also it behaves like a real server by declaring routes to files in the FS etc..
